# Generated by Django 3.1.5 on 2021-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_remove_subscription_validity_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="last_renewed_at",
            field=models.DateTimeField(null=True, verbose_name="최근 구독 갱신 날짜"),
        ),
    ]
