version: '3.4'

services:
  api:
    build:
      context: .
      target: builder
    image: zezaeoh/ggongsul-api:dev
    container_name: ggongsul-api
    environment:
      APP_ENV: development
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    command: "/app/bin/docker-entrypoint"
