# Generated by Django 3.1.3 on 2020-12-25 15:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="약관 이름")),
                (
                    "body",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="약관 본문"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
            ],
            options={
                "verbose_name": "이용 약관",
                "verbose_name_plural": "이용 약관",
            },
        ),
    ]
