# Generated by Django 3.1.3 on 2020-11-22 15:29

from django.db import migrations, models
import django.db.models.deletion
import ggongsul.partner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="업체 상호명")),
                ("address", models.CharField(max_length=128, verbose_name="업체 주소")),
                ("contact_name", models.CharField(max_length=16, verbose_name="대표 이름")),
                (
                    "contact_phone",
                    models.CharField(max_length=16, verbose_name="대표 연락처"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="업체 활성화 여부"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
            ],
            options={
                "verbose_name": "업체 정보",
                "verbose_name_plural": "업체 정보",
            },
        ),
        migrations.CreateModel(
            name="PartnerCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="업체를 분류할 카테고리 이름입니다.",
                        max_length=10,
                        verbose_name="카테고리 이름",
                    ),
                ),
                (
                    "icon_img",
                    models.ImageField(
                        default="/image/category/default.png",
                        help_text="카테고리를 표현할 간단한 이미지입니다.",
                        upload_to="",
                        verbose_name="카테고리 이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리",
            },
        ),
        migrations.CreateModel(
            name="PartnerDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_token",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="업체 관리용 비밀 토큰"
                    ),
                ),
                ("store_phone", models.CharField(max_length=16, verbose_name="매장 연락처")),
                ("short_desc", models.CharField(max_length=64, verbose_name="한 줄 소개")),
                ("detail_desc", models.TextField(verbose_name="상세 소개")),
                (
                    "ext_close_info",
                    models.CharField(
                        blank=True,
                        help_text="업체의 추가 휴무정보를 입력합니다.",
                        max_length=128,
                        null=True,
                        verbose_name="추가 휴무 정보",
                    ),
                ),
                (
                    "open_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="오픈시간"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="마감시간"
                    ),
                ),
                (
                    "img_main",
                    models.ImageField(
                        default="/image/partner/default.png",
                        help_text="업체의 대표 이미지입니다.",
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 대표 이미지",
                    ),
                ),
                (
                    "img_store_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 매장 사진 01",
                    ),
                ),
                (
                    "img_store_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 매장 사진 02",
                    ),
                ),
                (
                    "img_store_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 매장 사진 03",
                    ),
                ),
                (
                    "img_store_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 매장 사진 04",
                    ),
                ),
                (
                    "img_store_5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 매장 사진 05",
                    ),
                ),
                (
                    "img_menu_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 메뉴 사진 01",
                    ),
                ),
                (
                    "img_menu_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 메뉴 사진 02",
                    ),
                ),
                (
                    "img_menu_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 메뉴 사진 03",
                    ),
                ),
                (
                    "img_menu_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 메뉴 사진 04",
                    ),
                ),
                (
                    "img_menu_5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ggongsul.partner.models.PathAndRename(
                            "/image/partner/"
                        ),
                        verbose_name="업체 메뉴 사진 05",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="해당 업체의 카테고리입니다.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partners",
                        to="partner.partnercategory",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="partner.partner",
                        verbose_name="업체",
                    ),
                ),
            ],
            options={
                "verbose_name": "업체 상세 정보",
                "verbose_name_plural": "업체 상세 정보",
            },
        ),
    ]
