# Generated by Django 3.1.3 on 2020-12-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnercategory",
            options={"verbose_name": "업체 분류", "verbose_name_plural": "업체 분류"},
        ),
        migrations.AddField(
            model_name="partnerdetail",
            name="offer_type",
            field=models.IntegerField(
                choices=[(1, "한 명당 한병"), (2, "두 명당 한병"), (3, "무제한 제공")],
                default=1,
                help_text="추후 언제든지 변경 가능합니다.",
                verbose_name="술 제공 유형",
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="category",
            field=models.ForeignKey(
                help_text="해당 업체의 카테고리입니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners",
                to="partner.partnercategory",
                verbose_name="매장 분류",
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="detail_desc",
            field=models.TextField(
                help_text="예) 트랜디한 레트로감성 용범이네 인계동껍데기!! 벌집껍데기를 비롯하여 항정살껍데기가 추천메뉴(대표메뉴)입니다. 비빔국수와 함께 드시면 더욱더 환상적인 맛을 느끼실 수 있습니다.",
                verbose_name="상세 매장 설명",
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="end_time",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="마감시간"
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="ext_close_info",
            field=models.CharField(
                blank=True,
                help_text="예) 매주 월요일 휴무, 일요일 10시 마감",
                max_length=128,
                null=True,
                verbose_name="매장 추가 휴무 정보",
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="open_time",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="오픈시간"
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="short_desc",
            field=models.CharField(
                help_text="예) 벌집껍데기 구워주는 곳, 레트로 감성 맛집",
                max_length=64,
                verbose_name="간단 매장 설명",
            ),
        ),
        migrations.AlterField(
            model_name="partnerdetail",
            name="store_phone",
            field=models.CharField(
                help_text="예) 02-1010-2020", max_length=16, verbose_name="매장 전화번호"
            ),
        ),
    ]
