# Generated by Django 3.1.3 on 2020-12-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_auto_20201205_1630"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_agreed_at",
                    models.DateTimeField(null=True, verbose_name="정책 동의 날짜"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to="partner.partner",
                        verbose_name="동의서",
                    ),
                ),
            ],
            options={
                "verbose_name": "이용약관 동의서",
                "verbose_name_plural": "이용약관 동의서",
            },
        ),
    ]
