# Generated by Django 3.1.3 on 2020-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0003_partneragreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=8, null=True, verbose_name="위도"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="경도"
            ),
        ),
    ]
