# Generated by Django 3.1.3 on 2020-12-25 17:09

from django.db import migrations, models
import ggongsul.partner.models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0004_auto_20201212_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerdetail",
            name="img_price_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ggongsul.partner.models.PathAndRename("/image/partner/"),
                verbose_name="업체 가격표(메뉴판) 사진 01",
            ),
        ),
        migrations.AddField(
            model_name="partnerdetail",
            name="img_price_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ggongsul.partner.models.PathAndRename("/image/partner/"),
                verbose_name="업체 가격표(메뉴판) 사진 02",
            ),
        ),
        migrations.AddField(
            model_name="partnerdetail",
            name="img_price_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ggongsul.partner.models.PathAndRename("/image/partner/"),
                verbose_name="업체 가격표(메뉴판) 사진 03",
            ),
        ),
    ]
