# Generated by Django 3.1.3 on 2021-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0005_auto_20201225_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partneragreement",
            name="policy_agreed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="정책 동의 날짜"),
        ),
    ]
