# Generated by Django 3.1.3 on 2021-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_auto_20210103_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="cert_num",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="업체 인증 번호"
            ),
        ),
    ]
