# Generated by Django 3.1.3 on 2021-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_review_visitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="deleted_on",
            field=models.DateTimeField(null=True, verbose_name="삭제 날짜"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
    ]
