# Generated by Django 3.1.3 on 2021-01-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_auto_20210116_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제 날짜"),
        ),
    ]
