# Generated by Django 3.1.3 on 2020-12-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_auto_20201220_1829"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_agreed_at",
                    models.DateTimeField(null=True, verbose_name="이용약관 동의 날짜"),
                ),
                (
                    "privacy_agreed_at",
                    models.DateTimeField(null=True, verbose_name="개인정보 이용 동의 날짜"),
                ),
                (
                    "adv_agreed_yn",
                    models.BooleanField(default=False, verbose_name="광고 수신 동의 여부"),
                ),
                (
                    "adv_agreed_at",
                    models.DateTimeField(null=True, verbose_name="광고 수신 동의 날짜"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="동의서",
                    ),
                ),
            ],
            options={
                "verbose_name": "이용약관 동의서",
                "verbose_name_plural": "이용약관 동의서",
            },
        ),
    ]
