# Generated by Django 3.1.5 on 2021-02-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ggongsul.member.models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_auto_20201225_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberagreement",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreement",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="memberdetail",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.CreateModel(
            name="MemberProfileImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=ggongsul.member.models.PathAndRename(
                            "/image/member/"
                        ),
                        verbose_name="사용자 프로필 사진",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_image",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필 사진",
                "verbose_name_plural": "사용자 프로필 사진",
            },
        ),
    ]
