# Generated by Django 3.1.5 on 2021-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0006_auto_20210220_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberdetail",
            name="recommended_place",
            field=models.CharField(max_length=150, null=True, verbose_name="추천 장소"),
        ),
    ]
