# Generated by Django 3.1.3 on 2021-01-16 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_auto_20210116_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
