# Generated by Django 3.1.3 on 2021-01-17 09:38

from django.db import migrations, models
import django.db.models.deletion
import ggongsul.community.models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_auto_20210116_2329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=ggongsul.community.models.PathAndRename(
                            "/image/post/"
                        ),
                        verbose_name="게시글 사진",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 날짜"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="최근 정보 변경 날짜"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 이미지",
                "verbose_name_plural": "게시글 이미지",
            },
        ),
    ]
